import { useState } from 'react';
import type { AccessibilityIssue } from '@/lib/types';
import { getSettings, cacheFix, getCachedFix } from '@/lib/storage';
import { generateFix } from '@/lib/ai/client';
import { usePanelStore } from '../store';
import { SparkleIcon } from './icons';

function CopyButton({ text }: { text: string }) {
  const [copied, setCopied] = useState(false);
  return (
    <button
      type="button"
      className="btn-ghost text-xs"
      onClick={async () => {
        await navigator.clipboard.writeText(text);
        setCopied(true);
        setTimeout(() => setCopied(false), 1500);
      }}
    >
      {copied ? 'Copied' : 'Copy fix'}
    </button>
  );
}

export function AIFixPanel({ issue }: { issue: AccessibilityIssue }) {
  const fix = usePanelStore((s) => s.fixes[issue.id]);
  const loading = usePanelStore((s) => s.fixLoading[issue.id]);
  const error = usePanelStore((s) => s.fixError[issue.id]);
  const { setFix, setFixLoading, setFixError } = usePanelStore.getState();

  const requestFix = async () => {
    setFixLoading(issue.id, true);
    try {
      const cached = await getCachedFix(issue.id);
      if (cached) {
        setFix(issue.id, cached);
        return;
      }
      const settings = await getSettings();
      const generated = await generateFix(issue, settings);
      await cacheFix(generated);
      setFix(issue.id, generated);
    } catch (err) {
      setFixError(issue.id, err instanceof Error ? err.message : String(err));
    }
  };

  if (!fix && !loading && !error) {
    return (
      <button type="button" className="btn-primary w-full text-xs" onClick={requestFix}>
        <SparkleIcon />
        Generate AI fix
      </button>
    );
  }

  if (loading) {
    return (
      <div className="flex items-center gap-2 rounded-lg bg-brand-50 px-3 py-2 text-xs text-brand-700 dark:bg-brand-900/30 dark:text-brand-200">
        <span className="h-3 w-3 animate-spin rounded-full border-2 border-brand-400 border-t-transparent" />
        A11yFix AI is analyzing your markup…
      </div>
    );
  }

  if (error) {
    return (
      <div className="space-y-2 rounded-lg bg-red-50 px-3 py-2 text-xs text-red-700 dark:bg-red-950/40 dark:text-red-300">
        <p>{error}</p>
        <button type="button" className="btn-ghost text-xs" onClick={requestFix}>
          Retry
        </button>
      </div>
    );
  }

  return (
    <div className="space-y-3 rounded-lg border border-brand-200 bg-brand-50/50 p-3 dark:border-brand-900 dark:bg-brand-950/20">
      <div>
        <p className="mb-1 flex items-center gap-1.5 text-xs font-semibold text-brand-700 dark:text-brand-300">
          <SparkleIcon /> What a real user experiences
        </p>
        <p className="text-xs text-slate-600 dark:text-slate-300">{fix.explanation}</p>
      </div>

      <div>
        <div className="mb-1 flex items-center justify-between">
          <span className="text-xs font-semibold text-slate-700 dark:text-slate-200">
            Suggested fix
          </span>
          <CopyButton text={fix.codeFix} />
        </div>
        <pre className="max-h-56 overflow-auto rounded-md bg-slate-900 p-3 text-[11px] leading-relaxed text-slate-100">
          <code>{fix.codeFix}</code>
        </pre>
      </div>

      {fix.rationale.length > 0 && (
        <ul className="list-inside list-disc space-y-0.5 text-[11px] text-slate-500 dark:text-slate-400">
          {fix.rationale.map((point, index) => (
            <li key={index}>{point}</li>
          ))}
        </ul>
      )}
      <p className="text-right text-[10px] text-slate-400">Generated by {fix.model}</p>
    </div>
  );
}
